from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .base import BaseType


@dataclass(kw_only=True)
class InputFileGenerated(BaseType):
    """
    A file generated by the application. The application must handle updates updateFileGenerationStart and updateFileGenerationStop to generate the file when asked by TDLib
    """

    __type__: Literal["inputFileGenerated"] = "inputFileGenerated"

    original_path: str
    """Local path to a file from which the file is generated. The path doesn't have to be a valid path and is used by TDLib only to detect name and MIME type of the generated file"""
    conversion: str
    """String specifying the conversion applied to the original file; must be persistent across application restarts. Conversions beginning with '#' are reserved for internal TDLib usage"""
    expected_size: int
    """Expected size of the generated file, in bytes; pass 0 if unknown"""
