from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .base import BaseType


@dataclass(kw_only=True)
class InputFileGenerated(BaseType):
    """
    A file generated by the application
    """

    __type__: Literal["inputFileGenerated"] = "inputFileGenerated"

    original_path: str | None = None
    """Local path to a file from which the file is generated; may be empty if there is no such file"""
    conversion: str
    """String specifying the conversion applied to the original file; must be persistent across application restarts. Conversions beginning with '#' are reserved for internal TDLib usage"""
    expected_size: int
    """Expected size of the generated file, in bytes; 0 if unknown"""
